### PR TITLE
Create .bower.json

### PR DESCRIPTION
**Pull request by Koli14**
Bower makes life easier.

### CODE REVIEW

**Comment by blueimp** [comment]
The bower config file has been removed on purpose: 23f245eda3f8c788431ba524bc70e7740a80cd4b
With the latest version of NPM and its support for flat dependency trees, I don't see the need for bower anymore.

**Comment by sebastian-marinescu** [comment]
I actually also think it should still be available as bower package. Why shouldn't it? 
Bower is still being used and will still be used for a long time, I think. 

In my case I'm used to having my frontend-packages in a directory I specified via my .bowerrc config-file. Since you took it down from bower I would manually download it and put it in my components-folder, but it would be easier and much more convenient to just type in one line of code.

**Comment by blueimp** [comment]
Actually you can still use bower to install any project from GitHub without those projects having to provide a bower config file, e.g.:

```
bower install blueimp/Gallery
```

http://bower.io/docs/api/#install

**Comment by sebastian-marinescu** [comment]
Oh, I didn't check and didn't know, thanks. I just assumed it, because the package is not listed:
http://bower.io/search/?q=blueimp

**Comment by blueimp** [comment]
I guess it only lists the projects providing a bower config file, but it still allows installing other projects regardless.

**Comment by Koli14** [comment]
@blueimp 
Then can you pls help me?
I use [Roots/Sage](https://github.com/roots/sage) wordpress starter theme, which is using gulp.
I tried: `npm install --save  blueimp-gallery`, and now blueimp-gallery is in my `node_modules` directory, but gulp do not add it's files to my css and js files. What shall I do?

**Pull request closed without merging**
