### PR TITLE
Add Delete image

### PR DESCRIPTION
**Pull request by Snow4e**
Hi,

Can you add "X" for delete an image of gallery with id?

when i press X button :
`<form class='form-horizontal' role='form' method='post' action='/ServiceGallery.php'>
    <button class='bot-ico' type='submit' value='" . $image['ID'] ."' name='imageid'>
 </button>
    <input type='HIDDEN' name='web_act' value='web_gallery_action_delete' />
    </form>\n";`

(sorry for bad english :+1:   )

### CODE REVIEW

**Comment by blueimp** [comment]
Please don't misuse the pull request feature.

As to your question, there's no reason that you couldn't add this feature in your own custom implementation.

**Comment by Snow4e** [comment]
sorry i am new in github. so It is not the right place to write?

**Comment by blueimp** [comment]
Here you can find some documentation about the collaboration tools of Github:
https://help.github.com/categories/collaborating-on-projects-using-issues-and-pull-requests/

In short, use pull requests if you yourself have contributed code to the project which might be valuable to the broader community.

Other projects also have issue trackers, where it's possible to report issues and some also accept suggestions for new features there.  
This project does not have such an issue tracker and only provides the possibility to open pull requests with no guarantee of accepting them.

Generally, I provide my open source projects without support guarantee, as it's simply too time consuming for me.

Thanks for your understanding.

**Comment by Snow4e** [comment]
Hi sebastian,

Thanks for that, i am newbi of github. So it is impossible ask for add delete image of my project true ? and another ask, its isnt possibile connect together various gallery with different id like :
<div id="fruits">
<a href="images/banana.jpg" title="Banana" data-gallery="#blueimp-gallery-fruits">
Banana
</a>
<a href="images/apple.jpg" title="Apple" data-gallery="#blueimp-gallery-fruits">
Apple
</a>
</div>
<div id="vegetables">
<a href="images/tomato.jpg" title="Tomato" data-gallery="#blueimp-gallery-vegetables">
Tomato
</a>
<a href="images/onion.jpg" title="Onion" data-gallery="#blueimp-gallery-vegetables">
Onion
</a>
</div>



thanks for patienceIl 15 giugno 2016 19:00:44 +02:00, Sebastian Tschan <notifications@github.com> ha scritto:

**Pull request closed without merging**
