### PR TITLE
Convert all CSS files to LESS files

### PR DESCRIPTION
**Pull request by maxkoryukov**
Hello!

This PR is about using LESS instead of CSS.

1. All CSS files was converted to LESS
2. Some LESS-variables was added:
    * `@bi-image-path` - allows to set custom path to BlueImp images

### CODE REVIEW

**Comment by arturmamedov** [comment]
And who wont  to use CSS?

**Comment by maxkoryukov** [comment]
@arturmamedov , I think, next step: provide build script for this lib.

In this case, two versions of the **BlueImp Gallery** will exists (_both will be synced and always up to date_):
* less
* css

The algorithm is the following:
1. Users: install the lib (from npm/bower/...). Further, he should use existing CSS files, **or** include attached `less` files to the custom build (I prefer second way).
2. Developers of the BlueImp-Gallery: just add fixes and improvements to the `.less` files (not to the `.css`)

**Comment by blueimp** [comment]
Thanks for your contribution, @maxkoryukov.
However I prefer to keep the CSS files as is, as it allows people to use this library without the LESS requirement.

**Comment by maxkoryukov** [comment]
@blueimp, ok.

I have the other proposal: I could integrate this repo with Travis CI (or any other). Travis will build the sources (LESS files) on each commit to master (or for tags, we could discuss conditions of the build), and append all required files to the new release of the Gallery. Generated files:
* CSS
* minified CSS
* images
* minified JS

Additionaly, we will open the way for continuous testing and linting. And, as I know, Travis is able to publish packages to NPM (on condition), and, possibly, to Bower (I am not sure about Bower).

I am asking, because I use Gallery as a source-dependency, including some files to custom build. And I don't want to maintain my own repo)) I'am really like your library)))

Will you merge **LESS Pull Request** with Travis integration? Or this way is not interesting too?

**Comment by maxkoryukov** [comment]
@blueimp, are there any thoughts about prev. comment?

**Comment by blueimp** [comment]
Sorry @maxkoryukov, like you I want to keep my maintenance overhead small and therefore don't want to include any additional build steps or change the code organisation of this repo in any major way.

**Comment by maxkoryukov** [comment]
sad, but accepted; you are the author and owner..

**Pull request closed without merging**
