### PR TITLE
fixed click handler for video gallery items

### PR DESCRIPTION
**Pull request by mtyeh411**
This commit fixes the `closeOnSlideClick` condition of the `handleClick`
function for video gallery items. `closeOnSlideClick` is only reached if the
`parent` is equal to the slide container (`.slides`).

The `parent` is set to the parentNode of
the event target, which is fine for image gallery items since they
adhere to the following general DOM structure:

```
<div class="slides">
  <div class="slide">
    <img src="...">
  </div>
</div>
```

However, this is problematic for video gallery items since they adhere
to the following general DOM structure:

```
<div class="slides">
  <div class="slide">
    <div class="video-content slide-content">
      <img src="...">
    </div>
  </div>
</div>
```

In that scenario, the click event can be triggered on the `.video-content`
div rather than the `.slide` div. This commit looks for the closest
`.slides` container of the click event target and sets that to parent.

### CODE REVIEW

**Comment by mtyeh411** [comment]
NOT READY FOR MERGE

**Comment by blueimp** [comment]
Could you update your pull request to solve the merge conflicts?

**Comment by moneyDuo** [comment]
Hello , I want to know that does V3 format can play in this plugin?

**Comment by dkenzik** [comment]
@mtyeh411 - Fix your conflicts and re-PR?

**Comment by mtyeh411** [comment]
sure ... a little crazy lately ... i'll try to resolve this soon

**Comment by NeXTs** [comment]
Any updates on this PR?
At the moment it's impossible to change video position because clicking timeline triggers click event and plugin behaves as like I've clicked "close" video mode and returns to gallery mode. Does someone else experience same behaviour?

video

Chrome 48.0.2564.97 m, win7

**Comment by blueimp** [comment]
Unfortunately, this approach will break the existing functionality.
To actually solve this, the best way would be to adjust the `slide-content` (or `video-content`) area, so it doesn't take up the whole space. Then clicking on the background not occupied by the video placeholder) would actually target the slide and behave as expected.
Therefore I'll close this ticket here but a different approach fixing this would be welcome.

**Pull request closed without merging**
